# main task for creation (add/update) of risk profiles
# this also sets a particular risk profile as "active"
# Example:
---
#- name: Get all attributes
#  isam:
#    appliance: "{{ inventory_hostname }}"
#    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
#    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
#    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
#    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
#    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
#    username:  "{{ username }}"
#    password:  "{{ password }}"
#    lmi_port:  "{{ port | default(omit) }}"
#    log:       "{{ log_level | default(omit) }}"
#    force:     "{{ force | default(omit) }}"
#    action: ibmsecurity.isam.aac.attributes.get_all
#    isamapi:
#  register: ret_obj_attributes

# now fill in the missing attributeId in the authentication_riskprofiles object
#- name: debug existing attributes
#  debug:
#    verbosity: 0
#    msg: "{{ ret_obj_attributes.data | to_nice_yaml }}"
#  when:
#    - ret_obj_attributes is defined

#- name: Create a separate object for the empty AttributeID
#  vars:
#      json_query1: "[?name == '{{ item.1.name | default(\'name\')}}'][{name: name, attributeID: id, weight: '{{ item.1.weight }}' }]"
#  set_fact:
# #    updated_risk_profiles: "{{ updated_risk_profiles|default([{name: {{ item.0.name | default('oops') }} }]) + (( item.1.attributeID is defined) | ternary( [{'name': item.1.name, 'attributeID': item.1.attributeID, 'weight': item.1.weight}], ret_obj_attributes.data | flatten | json_query(json_query1) | flatten )) }}"
# #   updated_risk_profiles: "{{ updated_risk_profiles|default([{'name': item.0.name | default('oops') }]) | combine([{'name': (item.0.name | default('oops')), 'attributes': ((item.1.attributeID is defined) | ternary( [{'name': item.1.name, 'attributeID': item.1.attributeID, 'weight': item.1.weight}], ret_obj_attributes.data | flatten | json_query(json_query1) | flatten )) }], recursive=True) }}"
# #    updated_risk_profiles: "{{ updated_risk_profiles|default([{'name': item.0.name | default('oops') }]) + [{'name': (item.0.name | default('oops')), 'attributes': ((item.1.attributeID is defined) | ternary( [{'name': item.1.name, 'attributeID': item.1.attributeID, 'weight': item.1.weight}], ret_obj_attributes.data | flatten | json_query(json_query1) | flatten )) }] }}"
#    updated_attributes_list: "{{ updated_attributes_list|default([]) +( [{'name': item.0.name, 'attributes': ((item.1.attributeID is defined) | ternary( [{'name': item.1.name, 'attributeID': item.1.attributeID, 'weight': item.1.weight}], ret_obj_attributes.data | flatten | json_query(json_query1) | flatten ) )}] ) }}"
#  with_subelements:
#    - "{{ authentication_riskprofiles }}"
#    - attributes
#    - skip_missing: true
#  loop_control:
#    label: "Loop risk profile {{ item.0.name | default('oops') }} - attribute {{ item.1.name | default('none') }}"
#  when:
#    - authentication_riskprofiles is defined
#    - item.1.attributeID is not defined
#
#- name: debug updated_attributes_list
#  debug:
#    verbosity: 0
#    msg: "{{ updated_attributes_list | to_nice_yaml }}"
#  when:
#    - updated_attributes_list is defined
#
#- name: now combine the attributes
#  set_fact:
#    authentication_riskprofiles: "{{ authentication_riskprofiles | combine(updated_attributes_list, recursive=True) }}"
#
#- name: debug authentication_riskprofiles
#  debug:
#    verbosity: 0
#    msg: "{{ authentication_riskprofiles | to_nice_yaml }}"
#  when:
#    - authentication_riskprofiles is defined

- name: Set Risk Profiles
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.colruyt_risk_profiles.set
    isamapi:
      name: "{{ item.name }}"
      active: "{{ item.active | default(False) }}"
      description: "{{ item.description | default('') }}"
      attributes: "{{ item.attributes | default([]) }}"
      new_name: "{{ item.new_name | default(omit) }}"
      predefined: "{{ item.predefined | default(omit) }}"
  with_items: "{{ authentication_riskprofiles }}"
  loop_control:
    label: "Risk profile: {{ item.name }} - active: {{ item.active | default('false') }}"
  when: authentication_riskprofiles is defined
  notify: Commit Changes

